### ISSUE TITLE
Función para hacer un scroll down 

### ISSUE THREAD

**Issue by sebastian-ramos1996** [HaifischCQBO/demoqa_company#12]
Compañeros, así logre realizar un scroll dentro de la página para evitar el problema con la publicidad. Espero les sea de utilidad.

public void scrollDown(){
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("window.scrollTo(0,500)"); // estos valores pueden variar dependiendo de la aplicación
    }

**Comment by HaifischCQBO** [comment]
Agregado a la rama master!
