### ISSUE TITLE
Problema con conflicto en rama

### ISSUE THREAD

**Issue by sebastian-ramos1996** [HaifischCQBO/demoqa_company#14]
Este mensaje apareció en mi rama después de actualizar información del repositorio:

This branch has conflicts that must be resolved
Use the [web editor](https://github.com/HaifischCQBO/demoqa_company/pull/7/conflicts) or the  to resolve conflicts.
Conflicting files
.idea/misc.xm

**Comment by HaifischCQBO** [comment]
Problema solucionado.
