### ISSUE TITLE
Error en ejecución 

### ISSUE THREAD

**Issue by Mcmvcvbro** [HaifischCQBO/demoqa_company#21]
Buen día compañeros para quienes presenten el error org.openqa.selenium.webdriverexception timed out waiting for driver server to start al momento de iniciar la ejecución de pruebas...

...Para solucionarlo es necesario agregar en SingletonDriver un tiempo de espera por medio del siguiente código

driver.manage().timedouts().implicitlyWait(15, TimeUnit.SECONDS);

importando

import java.util.concurrent.TimeUnit;

**Comment by HaifischCQBO** [comment]
Muy buena solucion!
